### ISSUE TITLE
Timeout Error if Connection Initiated While Server is Starting Up

### ISSUE THREAD

**Issue by adamkrellenstein** [eandersson/amqp-storm#8]
I'm seeing this in particular with Docker... I run `$ docker run -p 5672:5672 rabbitmq`, and then *before* RabbitMQ has had a chance to start up, I run `$ python3 -c "import amqpstorm; amqpstorm.Connection('localhost', 'guest', 'guest')"`. I get the following error *thirty* seconds later (well after RabbitMQ has finished starting): `amqpstorm.exception.AMQPConnectionError: Connection timed out`

Replicated in a single command:
```
$ > docker run -p 5672:5672 -d rabbitmq; sleep 1s; python -c "import amqpstorm; amqpstorm.Connection('localhost', 'guest', 'guest')"
31a4da1f7aa3015550be080af4bc4bb76f0540b323ca0935bbe88f4d1082b1b0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/amqpstorm/connection.py", line 65, in __init__
    self.open()
  File "/usr/lib/python3.5/site-packages/amqpstorm/connection.py", line 123, in open
    self._wait_for_connection_to_open()
  File "/usr/lib/python3.5/site-packages/amqpstorm/connection.py", line 227, in _wait_for_connection_to_open
    raise AMQPConnectionError('Connection timed out')
amqpstorm.exception.AMQPConnectionError: Connection timed out
$ >
```

If I `sleep` for, say, *five* seconds after starting the Docker container, then the connection gets made just fine, and immediately.

**Comment by eandersson** [comment]
Interesting. I could see some odd scenarios where this would happen, but when I ran it under Ubuntu with AMQP-Storm 1.2.5 I got the intended result.
````
$ > docker run -p 5672:5672 -d rabbitmq; sleep 1s; python -c "import amqpstorm; amqpstorm.Connection('localhost', 'guest', 'guest')"
f19c241516011997ebf68ba64fac53f7048430fdf9dd2b4814088fe438ba3529
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/amqpstorm/connection.py", line 65, in __init__
    self.open()
  File "/usr/local/lib/python2.7/dist-packages/amqpstorm/connection.py", line 123, in open
    self._wait_for_connection_to_open()
  File "/usr/local/lib/python2.7/dist-packages/amqpstorm/connection.py", line 228, in _wait_for_connection_to_open
    self.check_for_errors()
  File "/usr/local/lib/python2.7/dist-packages/amqpstorm/connection.py", line 167, in check_for_errors
    super(Connection, self).check_for_errors()
  File "/usr/local/lib/python2.7/dist-packages/amqpstorm/base.py", line 82, in check_for_errors
    raise why
amqpstorm.exception.AMQPConnectionError: [Errno 104] Connection reset by peer
````
My guess would be that it's getting stuck trying to open the socket. Try setting the ```timeout``` to 1.

```
docker run -p 5672:5672 -d rabbitmq; sleep 1s; python -c "import amqpstorm; amqpstorm.Connection('localhost', 'guest', 'guest', timeout=1)"
```

**Comment by eandersson** [comment]
If you have time, could you try the above patch? This would still throw an exception if the connection isn't yet ready, but hopefully you won't have to wait 30s seconds.to know.

**Comment by eandersson** [comment]
Let me know if this is still an issue.
